env:
    # Twrp Sync Repository
    TWRP_SYNC: https://github.com/Arafattex/platform_manifest_twrp_aosp.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: 1119385461
    TG_TOKEN: 2044609608:AAE-lWE9ZXhcLVcWKj5F4DMDYFU7eFIQOm0

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/Arafattex/OrangeFox-CI/shas/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/Arafattex/OrangeFox-CI/shas/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/Arafattex/OrangeFox-CI/shas/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/Arafattex/OrangeFox-CI/shas/scripts/upload.sh | bash
